"""initial schema - all tables

Revision ID: 5cab6c1da0bc
Revises: 
Create Date: 2026-03-15 16:18:35.200281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cab6c1da0bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=255), nullable=True),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('admin', 'voter'), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('student_id', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('elections',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('election_type', sa.Enum('single_seat', 'multi_seat'), nullable=False),
    sa.Column('visibility_type', sa.Enum('private', 'public'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('eligibility_merkle_root', sa.String(length=66), nullable=True),
    sa.Column('location_rule_hash', sa.String(length=66), nullable=True),
    sa.Column('eligibility_locked', sa.Boolean(), nullable=False),
    sa.Column('candidates_locked', sa.Boolean(), nullable=False),
    sa.Column('candidate_list_hash', sa.String(length=66), nullable=True),
    sa.Column('contract_address', sa.String(length=42), nullable=True),
    sa.Column('contract_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_admin', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'completed'), nullable=False),
    sa.Column('results_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('election_id')
    )
    op.create_table('constituencies',
    sa.Column('constituency_id', sa.String(length=36), nullable=False),
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('constituency_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], ),
    sa.PrimaryKeyConstraint('constituency_id')
    )
    op.create_table('vote_transactions',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('voter_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('blockchain_tx_hash')
    )
    op.create_table('voter_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('id_verification', 'address_verification'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('constituency_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_identifier', sa.String(length=100), nullable=True),
    sa.Column('party_name', sa.String(length=255), nullable=True),
    sa.Column('symbol_url', sa.String(length=500), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('manifesto', sa.Text(), nullable=True),
    sa.Column('candidate_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'withdrawn', 'disqualified'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.constituency_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('election_voters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('constituency_id', sa.String(length=36), nullable=False),
    sa.Column('voter_identifier', sa.String(length=255), nullable=False),
    sa.Column('hashed_identifier', sa.String(length=255), nullable=False),
    sa.Column('authorization_status', sa.Enum('authorized'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.constituency_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('election_voters')
    op.drop_table('candidates')
    op.drop_table('voter_verifications')
    op.drop_table('vote_transactions')
    op.drop_table('constituencies')
    op.drop_table('elections')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
