"""add failed_attempts to email_otps

Revision ID: 63e8dce10c9e
Revises: 7b107e63a3e2
Create Date: 2026-07-24 11:02:39.686615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e8dce10c9e'
down_revision = '7b107e63a3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
