"""add deleted column to organizations

Revision ID: 804ff95a656a
Revises: 8bb1f5d1446f
Create Date: 2026-07-23 15:08:06.953161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804ff95a656a'
down_revision = '8bb1f5d1446f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
