"""add_constituency_id_to_voter_verifications_and_location_rules

Revision ID: a4f7b01111ab
Revises: c64fe450b1e3
Create Date: 2026-07-24 12:11:34.954694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f7b01111ab'
down_revision = 'c64fe450b1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_rules', sa.Text(), nullable=True))

    with op.batch_alter_table('voter_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constituency_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'constituencies', ['constituency_id'], ['constituency_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('constituency_id')

    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.drop_column('location_rules')

    # ### end Alembic commands ###
