"""add_constituency_code

Revision ID: ac21778a1df7
Revises: a4f7b01111ab
Create Date: 2026-07-27 15:23:17.450764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac21778a1df7'
down_revision = 'a4f7b01111ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constituency_code', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.drop_column('constituency_code')

    # ### end Alembic commands ###
