"""add aadhaar_hash to voter_verifications

Revision ID: c64fe450b1e3
Revises: 63e8dce10c9e
Create Date: 2026-07-24 11:32:41.370933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64fe450b1e3'
down_revision = '63e8dce10c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aadhaar_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_verifications', schema=None) as batch_op:
        batch_op.drop_column('aadhaar_hash')

    # ### end Alembic commands ###
